services:
  postgres:
    image: postgres:16-alpine
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  postgres-notifications:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: notifications_db
    ports:
      - "5433:5432"
    volumes:
      - pg_notifications_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d notifications_db"]
      interval: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      retries: 10

  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  writer-service:
    build: ./writer-service
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  inventory-service:
    build: ./inventory-service
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      postgres-notifications:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  analytics-service:
    build: ./analytics-service
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
    depends_on:
      rabbitmq:
        condition: service_healthy

  payments-service:
    build: ./payments-service
    env_file: .env
    environment:
      PYTHONUNBUFFERED: "1"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  pg_data:
  pg_notifications_data: